name: Deploy production

on:
  push:
    tags:
      - "app-v*"

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy app (mainnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-apps"
          script_install: pnpm install
          script_build: pnpm app build:mainnet
          dist_path: apps/helixbox-app/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy app (testnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "testnet.app.helix.box"
          project_name: "helix-apps-test"
          script_install: pnpm install
          script_build: pnpm app build:testnet
          dist_path: apps/helixbox-app/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  publish-ipfs:
    name: Publish ipfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Publish ipfs
        env:
          FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          pnpm install
          pnpm app build:mainnet
          mv apps/helixbox-app/fleek.config.json apps/helixbox-app/dist
          cd apps/helixbox-app/dist

          npm i -g @fleek-platform/cli
          fleek projects switch --id=clwordxrq0003igm26h2r52n1
          fleek sites deploy

          
