name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install
        run: pnpm install

      - name: Lint and Test
        run: |
          pnpm run lint
          pnpm run test

      - name: Build
        run: |
          pnpm run build
