name: CI

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Install
        run: pnpm install

      - name: Lint and Test
        run: |
          pnpm run lint
          pnpm run test

      - name: Build
        run: |
          pnpm run build

  publish-ipfs:
    name: Publish ipfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Publish ipfs
        env:
          FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
        run: |
          pnpm install
          pnpm web build:mainnet
          mv apps/web/fleek.config.json apps/web/dist
          cd apps/web/dist

          npm i -g @fleek-platform/cli
          fleek projects switch --id=clwordxrq0003igm26h2r52n1
          fleek sites deploy
          

