name: Deploy Production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-package:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy Helix (mainnet)
        with:
          node_verson: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-apps"
          script_install: npm i
          script_build: npm run build:mainnet
          dist_path: dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy Helix (testnet)
        with:
          node_verson: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "testnet.helixbridge.app"
          project_name: "helix-apps-test"
          script_install: npm i
          script_build: npm run build:testnet
          dist_path: dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
