name: Deploy staging

on:
  push:
    branches: [main, master]
  pull_request:
    types: [opened, synchronize, ready_for_review]
    branches:
      - main

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - apps
          - helix
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            packages/shared
            packages/${{ matrix.package }}

      - name: Better project name
        id: better-name
        run: |
          PACKAGE_NAME="${{ matrix.package }}"
          if [[ "$PACKAGE_NAME" == "helix" ]]; then
            PACKAGE_NAME=ui
          fi
          echo "The output package name is ${PACKAGE_NAME}"
          echo ''
          echo "::set-output name=NAME::${PACKAGE_NAME}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }}
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-${{ steps.better-name.outputs.NAME }}-stg"
          project_name: "helix-${{ steps.better-name.outputs.NAME }}"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }} (test)
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-${{ steps.better-name.outputs.NAME }}-test-stg"
          project_name: "helix-${{ steps.better-name.outputs.NAME }}-test"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

