name: Deploy development

on:
  pull_request:
  workflow_dispatch:

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Build
        run: |
          npm install
          npm run build:test
      - name: Upload
        uses: aquiladev/ipfs-action@master
        with:
          path: ./out
          service: pinata
          pinataKey: ${{ secrets.PINATA_KEY }}
          pinataSecret: ${{ secrets.PINATA_SECRET }}
