name: Deploy production

on:
  push:
    tags:
      - "v*"

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy web (mainnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-apps"
          script_install: pnpm install
          script_build: pnpm web build:mainnet
          dist_path: apps/web/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy web (testnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "testnet.helixbridge.app"
          project_name: "helix-apps-test"
          script_install: pnpm install
          script_build: pnpm web build:testnet
          dist_path: apps/web/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

  publish-ipfs:
    name: Publish ipfs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Publish ipfs
        env:
          FLEEK_TOKEN: ${{ secrets.FLEEK_TOKEN }}
        run: |
          pnpm install @fleekxyz/cli --global
          fleek projects switch --id=clwordxrq0003igm26h2r52n1
          pnpm install
          pnpm web build:mainnet
          mv apps/web/fleek.config.json apps/web/dist
          cd apps/web/dist
          fleek sites deploy
          
