name: Deploy production

on:
  push:
    tags:
      - 'v*'

jobs:

  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - apps
          - helix
          
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Better project name
        id: better-name
        run: |
          PACKAGE_NAME="${{ matrix.package }}"
          if [[ "$PACKAGE_NAME" == "helix" ]]; then
            PACKAGE_NAME=ui
          fi
          echo "The output package name is ${PACKAGE_NAME}"
          echo ''
          echo "::set-output name=NAME::${PACKAGE_NAME}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }}
        if: contains(github.ref, matrix.package) || contains(github.ref, '-') == false
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-${{ steps.better-name.outputs.NAME }}"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }}
        if: contains(github.ref, 'apps') || contains(github.ref, '-') == false
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-${{ steps.better-name.outputs.NAME }}-test"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

