name: Deploy staging

on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: darwinia-network/devops
          path: .github

      - uses: ./.github/actions/smart-vercel
        name: Deploy helix
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg"
          project_name: "helix-apps"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy helix (test)
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg-test,testnet.helixbridge.app"
          project_name: "helix-apps-test"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

