name: Deploy production

on:
  push:
    tags:
      - 'v*'

jobs:

  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy helix
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-apps"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: ./.github/actions/smart-vercel
        name: Deploy (test)
        if: contains(github.ref, matrix.package) || contains(github.ref, '-') == false
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          prod_mode: true
          project_name: "helix-apps-test"
          script_run: false
          dist_path: .
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

