name: Deploy staging

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy web (mainnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg-mainnet"
          project_name: "helix-apps"
          script_install: pnpm install
          script_build: pnpm web build:mainnet
          dist_path: apps/web/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy web (testnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg-testnet"
          project_name: "helix-apps-test"
          script_install: pnpm install
          script_build: pnpm web build:testnet
          dist_path: apps/web/dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
