name: Deploy Staging

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy-package:
    name: Deploy Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy Helix (mainnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg-mainnet"
          project_name: "helix-apps"
          script_install: pnpm i
          script_build: pnpm run build:mainnet
          dist_path: dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

      - uses: darwinia-network/devops/actions/smart-vercel@main
        name: Deploy Helix (testnet)
        with:
          node_version: 20
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-stg-testnet"
          project_name: "helix-apps-test"
          script_install: pnpm i
          script_build: pnpm run build:testnet
          dist_path: dist
          enable_notify_slack: true
          slack_channel: helix-ui
          slack_webhook: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
