name: Deploy staging

on:
  push:
    branches: [main, master]

jobs:
  deploy-package:
    name: Deploy package
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - apps
          - helix
    steps:
      - uses: actions/checkout@v2

      - uses: actions/checkout@v2
        with:
          repository: itering/actions
          path: .github/actions
          persist-credentials: false
          ssh-key: "${{ secrets.ITERING_ACTIONS_DEPLOY_KEY }}"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v18.4
        with:
          files: |
            packages/shared
            packages/${{ matrix.package }}

      - name: Better project name
        id: better-name
        run: |
          PACKAGE_NAME="${{ matrix.package }}"
          if [[ "$PACKAGE_NAME" == "helix" ]]; then
            PACKAGE_NAME=ui
          fi
          echo "The output package name is ${PACKAGE_NAME}"
          echo ''
          echo "::set-output name=NAME::${PACKAGE_NAME}"

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }}
        id: smart-vercel
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-${{ steps.better-name.outputs.NAME }}-stg"
          project_name: "helix-${{ steps.better-name.outputs.NAME }}"
          script_run: false
          dist_path: .

      - uses: ./.github/actions/smart-vercel
        name: Deploy ${{ matrix.package }}
        id: smart-vercel
        if: steps.changed-files.outputs.any_changed == 'true' && matrix.package == 'app'
        with:
          vercel_token: ${{ secrets.VERCEL_TOKEN }}
          vercel_group: itering
          preview_output: true
          alias_domain: "helix-${{ steps.better-name.outputs.NAME }}-test-stg"
          project_name: "helix-${{ steps.better-name.outputs.NAME }}-test"
          script_run: false
          dist_path: .

      - name: Slack Notification
        uses: rtCamp/action-slack-notify@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          SLACK_CHANNEL: helix-ui
          SLACK_COLOR: ${{ job.status }}
          SLACK_ICON: https://avatars.githubusercontent.com/u/14985020?s=48&v=4
          SLACK_MESSAGE: "${{ steps.smart-vercel.outputs.PREVIEW_LINK }}"
          SLACK_TITLE: Preview
          SLACK_USERNAME: Vercel
          SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}

